### ISSUE TITLE
Unable to publish power bi files to service.

### ISSUE THREAD

**Issue by VenkatBB** [maikvandergaag/msft-extensions#405] opened 2022-05-10 13:05 UTC
**Power Bi Actions**

**I'm have been using DevOps to publish power bi files to power bi service, from past 4 days I'm unable to do this, when ever I try to commit, the pipeline is getting failed with the error "One or more errors occurred"
can some one help me to fix this.**

**Comment by DomBros** [comment] 2022-06-02 11:18
I have the same problem / error
Please give a hint where to look for the causes of the problem
I was configuring using (however, they differ):
https://medium.com/swlh/automate-you-power-bi-reports-deployment-using-azure-devops-5ada8915d401
https://www.youtube.com/watch?v=NnkZUZP_zdM

![image](https://user-images.githubusercontent.com/18525141/171617233-6b50eaab-994c-4e23-ad1c-313db3a9c208.png)
[ReleaseLogs_8.zip](https://github.com/maikvandergaag/msft-extensions/files/8823205/ReleaseLogs_8.zip)

**Comment by maikvandergaag** [comment] 2022-06-02 15:40
Could you also share a debug log?

**Comment by DomBros** [comment] 2022-06-03 07:10
thank you for the advise
i'm very new to the topic
I had problem with token

For someone who will search
for more logs turn on System.Debug
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=powershell

**Comment by DomBros** [comment] 2022-06-03 09:11
> **Power Bi Actions**
> 
> **I'm have been using DevOps to publish power bi files to power bi service, from past 4 days I'm unable to do this, when ever I try to commit, the pipeline is getting failed with the error "One or more errors occurred" can some one help me to fix this.**

Did you try to turn on System.Debug to see what is going on?

**Comment by maikvandergaag** [comment] 2022-06-16 19:08
@VenkatBB: Are you still having the issue? If yes please share more logs otherwise I will close the issue

**Comment by maikvandergaag** [comment] 2022-07-08 04:55
@paulmaksimovic turn on the debug logs to get more info.

**Comment by paulmaksimovic** [comment] 2022-07-11 15:35
Hello

apologies for the delay. Let me re-run this tonight with the additional log. Thanks for the assistance

**Comment by paulmaksimovic** [comment] 2022-07-12 09:00
Hello

Hopefully the attached will help.


Many Thanks

**Closed** 2022-08-05 06:07 UTC
Labels: help wanted, powerbiactions

**Comment by VenkatBB** [comment] 2022-10-11 08:17
***@***.***

***@***.***

Raw Log
***@***.***

***@***.***

2022-05-10T12:39:21.9481353Z ##[section]Starting: Agent job 1
2022-05-10T12:39:22.3140557Z ##[section]Starting: Initialize job
2022-05-10T12:39:22.3142101Z Agent name: 'Azure Pipelines 2'
2022-05-10T12:39:22.3142546Z Agent machine name: 'fv-az571-144'
2022-05-10T12:39:22.3142759Z Current agent version: '2.202.1'
2022-05-10T12:39:22.3177689Z ##[group]Operating System
2022-05-10T12:39:22.3177936Z Microsoft Windows Server 2022
2022-05-10T12:39:22.3178119Z 10.0.20348
2022-05-10T12:39:22.3178263Z Datacenter
2022-05-10T12:39:22.3178406Z ##[endgroup]
2022-05-10T12:39:22.3178580Z ##[group]Virtual Environment
2022-05-10T12:39:22.3178767Z Environment: windows-2022
2022-05-10T12:39:22.3178959Z Version: 20220503.1
2022-05-10T12:39:22.3179272Z Included Software: https://github.com/actions/virtual-environments/blob/win22/20220503.1/images/win/Windows2022-Readme.md
2022-05-10T12:39:22.3179701Z Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220503.1
2022-05-10T12:39:22.3180040Z ##[endgroup]
2022-05-10T12:39:22.3180436Z ##[group]Virtual Environment Provisioner
2022-05-10T12:39:22.3180653Z 1.0.0.0-main-20220421-1
2022-05-10T12:39:22.3180810Z ##[endgroup]
2022-05-10T12:39:22.3181624Z Current image version: '20220503.1'
2022-05-10T12:39:22.3189467Z Agent running as: 'VssAdministrator'
2022-05-10T12:39:22.3325311Z Prepare build directory.
2022-05-10T12:39:22.3568878Z Set build variables.
2022-05-10T12:39:22.3598892Z Download all required tasks.
2022-05-10T12:39:22.3705567Z Downloading task: PowerBIActions (5.4.32)
2022-05-10T12:39:25.2421335Z Checking job knob settings.
2022-05-10T12:39:25.2430475Z    Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY}
2022-05-10T12:39:25.2431605Z    Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG}
2022-05-10T12:39:25.2433139Z Finished checking job knob settings.
2022-05-10T12:39:25.2711267Z Start tracking orphan processes.
2022-05-10T12:39:25.2778518Z ##[section]Finishing: Initialize job
2022-05-10T12:39:25.3042307Z ##[section]Starting: Checkout ***@***.*** to s
2022-05-10T12:39:25.4553818Z ==============================================================================
2022-05-10T12:39:25.4554410Z Task         : Get sources
2022-05-10T12:39:25.4554847Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2022-05-10T12:39:25.4555109Z Version      : 1.0.0
2022-05-10T12:39:25.4555417Z Author       : Microsoft
2022-05-10T12:39:25.4555918Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2022-05-10T12:39:25.4556238Z ==============================================================================
2022-05-10T12:39:26.8820585Z Syncing repository: XXXXXXAN_QUALITY (Git)
2022-05-10T12:39:26.8825417Z Prepending Path environment variable with directory containing 'git.exe'.
2022-05-10T12:39:26.8832425Z ##[command]git version
2022-05-10T12:39:27.4363539Z git version 2.30.2.windows.1
2022-05-10T12:39:27.4384456Z ##[command]git lfs version
2022-05-10T12:39:29.0560201Z git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git a5e65851)
2022-05-10T12:39:29.0693143Z ##[command]git init "D:\a\1\s"
2022-05-10T12:39:29.3155124Z Initialized empty Git repository in D:/a/1/s/.git/
2022-05-10T12:39:29.3228036Z ##[command]git remote add origin https://XXXXXdataanddev.visualstudio.com/Power_BI/_git/XXXXXXAN_QUALITY<https://XXXXXXXXXXXXXXXXXXdataanddev.visualstudio.com/Power_BI/_git/XXXXXXXXXAN_QUALITY>
2022-05-10T12:39:29.3948936Z ##[command]git config gc.auto 0
2022-05-10T12:39:29.4557271Z ##[command]git config --get-all http.https://XXXXXdataanddev.visualstudio.com/Power_BI/_git/XXXXXXAN_QUALITY.extraheader
2022-05-10T12:39:29.4962060Z ##[command]git config --get-all http.extraheader
2022-05-10T12:39:29.5354187Z ##[command]git config --get-regexp .*extraheader
2022-05-10T12:39:29.5749956Z ##[command]git config --get-all http.proxy
2022-05-10T12:39:29.6141701Z ##[command]git config http.version HTTP/1.1
2022-05-10T12:39:29.6600594Z ##[command]git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
2022-05-10T12:39:31.2231487Z remote: Azure Repos
2022-05-10T12:39:31.3130288Z remote:
2022-05-10T12:39:31.3132607Z remote: Found 187 objects to send. (100 ms)
2022-05-10T12:39:31.4045040Z Receiving objects:   0% (1/187)
2022-05-10T12:39:31.4170794Z Receiving objects:   1% (2/187)
2022-05-10T12:39:31.4173972Z Receiving objects:   2% (4/187)
2022-05-10T12:39:31.4270908Z Receiving objects:   3% (6/187)
2022-05-10T12:39:31.6102632Z Receiving objects:   4% (8/187)
2022-05-10T12:39:31.6737330Z Receiving objects:   5% (10/187)
2022-05-10T12:39:31.7646401Z Receiving objects:   6% (12/187)
2022-05-10T12:39:31.7757506Z Receiving objects:   7% (14/187)
2022-05-10T12:39:31.9057516Z Receiving objects:   8% (15/187)
2022-05-10T12:39:31.9651334Z Receiving objects:   9% (17/187), 12.69 MiB | 25.17 MiB/s
2022-05-10T12:39:32.1523968Z Receiving objects:  10% (19/187), 12.69 MiB | 25.17 MiB/s
2022-05-10T12:39:32.2172570Z Receiving objects:  11% (21/187), 12.69 MiB | 25.17 MiB/s
2022-05-10T12:39:32.2386337Z Receiving objects:  12% (23/187), 12.69 MiB | 25.17 MiB/s
2022-05-10T12:39:32.2804229Z Receiving objects:  13% (25/187), 12.69 MiB | 25.17 MiB/s
2022-05-10T12:39:32.4132970Z Receiving objects:  14% (27/187), 12.69 MiB | 25.17 MiB/s
2022-05-10T12:39:32.4205207Z Receiving objects:  14% (28/187), 26.31 MiB | 26.10 MiB/s
2022-05-10T12:39:32.6298663Z Receiving objects:  15% (29/187), 26.31 MiB | 26.10 MiB/s
2022-05-10T12:39:32.6779886Z Receiving objects:  16% (30/187), 26.31 MiB | 26.10 MiB/s
2022-05-10T12:39:32.7946213Z Receiving objects:  17% (32/187), 26.31 MiB | 26.10 MiB/s
2022-05-10T12:39:32.9490599Z Receiving objects:  18% (34/187), 26.31 MiB | 26.10 MiB/s
2022-05-10T12:39:33.0583141Z Receiving objects:  19% (36/187), 36.99 MiB | 23.91 MiB/s
2022-05-10T12:39:33.1581247Z Receiving objects:  20% (38/187), 36.99 MiB | 23.91 MiB/s
2022-05-10T12:39:33.2078466Z Receiving objects:  21% (40/187), 36.99 MiB | 23.91 MiB/s
2022-05-10T12:39:33.2762538Z Receiving objects:  22% (42/187), 36.99 MiB | 23.91 MiB/s
2022-05-10T12:39:33.2904497Z Receiving objects:  23% (44/187), 36.99 MiB | 23.91 MiB/s
2022-05-10T12:39:33.4330291Z Receiving objects:  24% (45/187), 36.99 MiB | 23.91 MiB/s
2022-05-10T12:39:33.5241256Z Receiving objects:  25% (47/187), 36.99 MiB | 23.91 MiB/s
2022-05-10T12:39:33.7228437Z Receiving objects:  26% (49/187), 51.86 MiB | 25.05 MiB/s
2022-05-10T12:39:33.9396027Z Receiving objects:  27% (51/187), 51.86 MiB | 25.05 MiB/s
2022-05-10T12:39:33.9403808Z Receiving objects:  28% (53/187), 51.86 MiB | 25.05 MiB/s
2022-05-10T12:39:34.0213905Z Receiving objects:  29% (55/187), 51.86 MiB | 25.05 MiB/s
2022-05-10T12:39:34.0246295Z Receiving objects:  30% (57/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0247426Z Receiving objects:  31% (58/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0249174Z Receiving objects:  32% (60/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0250400Z Receiving objects:  33% (62/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0253344Z Receiving objects:  34% (64/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0260555Z Receiving objects:  35% (66/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0261595Z Receiving objects:  36% (68/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0262406Z Receiving objects:  37% (70/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0263207Z Receiving objects:  38% (72/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0264549Z Receiving objects:  39% (73/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0268543Z Receiving objects:  40% (75/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0269663Z Receiving objects:  41% (77/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0270473Z Receiving objects:  42% (79/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0271696Z Receiving objects:  43% (81/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0272686Z Receiving objects:  44% (83/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0274051Z Receiving objects:  45% (85/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0281288Z Receiving objects:  46% (87/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0289124Z Receiving objects:  47% (88/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0293278Z Receiving objects:  48% (90/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0294498Z Receiving objects:  49% (92/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0295552Z Receiving objects:  50% (94/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0296779Z Receiving objects:  51% (96/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0297661Z Receiving objects:  52% (98/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0308020Z Receiving objects:  53% (100/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0309406Z Receiving objects:  54% (101/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0313697Z Receiving objects:  55% (103/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0315117Z Receiving objects:  56% (105/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0316090Z Receiving objects:  57% (107/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0317320Z Receiving objects:  58% (109/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0318476Z Receiving objects:  59% (111/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0319628Z Receiving objects:  60% (113/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0322932Z Receiving objects:  61% (115/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0335200Z Receiving objects:  62% (116/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0336077Z Receiving objects:  63% (118/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0336872Z Receiving objects:  64% (120/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0337650Z Receiving objects:  65% (122/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0338438Z Receiving objects:  66% (124/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0339215Z Receiving objects:  67% (126/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0340954Z Receiving objects:  68% (128/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0342070Z Receiving objects:  69% (130/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0345749Z Receiving objects:  70% (131/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0346626Z Receiving objects:  71% (133/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0347693Z Receiving objects:  72% (135/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0348818Z Receiving objects:  73% (137/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0349735Z Receiving objects:  74% (139/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0391860Z Receiving objects:  75% (141/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0566735Z Receiving objects:  76% (143/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0571576Z Receiving objects:  77% (144/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0723598Z Receiving objects:  78% (146/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0726431Z Receiving objects:  79% (148/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0727306Z Receiving objects:  80% (150/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0728106Z Receiving objects:  81% (152/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0728875Z Receiving objects:  82% (154/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0729768Z Receiving objects:  83% (156/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0733158Z Receiving objects:  84% (158/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0733966Z Receiving objects:  85% (159/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0734752Z Receiving objects:  86% (161/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0735540Z Receiving objects:  87% (163/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0736304Z Receiving objects:  88% (165/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0737115Z Receiving objects:  89% (167/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.0740966Z Receiving objects:  90% (169/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.1491698Z Receiving objects:  91% (171/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.1496614Z Receiving objects:  92% (173/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.2039869Z Receiving objects:  93% (174/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.2041509Z Receiving objects:  94% (176/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.2878332Z Receiving objects:  95% (178/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.3668460Z Receiving objects:  96% (180/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.3669494Z Receiving objects:  97% (182/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.3702151Z Receiving objects:  98% (184/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.3703857Z Receiving objects:  99% (186/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.3704804Z Receiving objects: 100% (187/187), 63.86 MiB | 24.38 MiB/s
2022-05-10T12:39:34.3705878Z Receiving objects: 100% (187/187), 74.71 MiB | 25.14 MiB/s, done.
2022-05-10T12:39:34.3736696Z Resolving deltas:   0% (0/2)
2022-05-10T12:39:34.3748357Z Resolving deltas:  50% (1/2)
2022-05-10T12:39:34.3749984Z Resolving deltas: 100% (2/2)
2022-05-10T12:39:34.3750857Z Resolving deltas: 100% (2/2), done.
2022-05-10T12:39:34.5788179Z From https://XXXXXdataanddev.visualstudio.com/Power_BI/_git/XXXXXXAN_QUALITY<https://XXXXXXXXXXXXXXXXXXdataanddev.visualstudio.com/Power_BI/_git/XXXXXXXXXAN_QUALITY>
2022-05-10T12:39:34.5798947Z  * [new branch]      main       -> origin/main
2022-05-10T12:39:34.5802181Z  * [new branch]      master     -> origin/master
2022-05-10T12:39:34.6496288Z ##[command]git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin  +056a8dfab2e42329b9907adb7b679742c17cb760
2022-05-10T12:39:34.7533241Z From https://XXXXXdataanddev.visualstudio.com/Power_BI/_git/XXXXXXAN_QUALITY<https://XXXXXXXXXXXXXXXXXXdataanddev.visualstudio.com/Power_BI/_git/XXXXXXXXXAN_QUALITY>
2022-05-10T12:39:34.7534250Z  * branch            056a8dfab2e42329b9907adb7b679742c17cb760 -> FETCH_HEAD
2022-05-10T12:39:34.8110985Z ##[command]git checkout --progress --force 056a8dfab2e42329b9907adb7b679742c17cb760
2022-05-10T12:39:34.8831015Z Note: switching to '056a8dfab2e42329b9907adb7b679742c17cb760'.
2022-05-10T12:39:34.8833366Z
2022-05-10T12:39:34.8834507Z You are in 'detached HEAD' state. You can look around, make experimental
2022-05-10T12:39:34.8836577Z changes and commit them, and you can discard any commits you make in this
2022-05-10T12:39:34.8837395Z state without impacting any branches by switching back to a branch.
2022-05-10T12:39:34.8837926Z
2022-05-10T12:39:34.8838582Z If you want to create a new branch to retain commits you create, you may
2022-05-10T12:39:34.8839326Z do so (now or later) by using -c with the switch command. Example:
2022-05-10T12:39:34.8839923Z
2022-05-10T12:39:34.8840600Z   git switch -c <new-branch-name>
2022-05-10T12:39:34.8841077Z
2022-05-10T12:39:34.8841652Z Or undo this operation with:
2022-05-10T12:39:34.8842097Z
2022-05-10T12:39:34.8842652Z   git switch -
2022-05-10T12:39:34.8843078Z
2022-05-10T12:39:34.8843756Z Turn off this advice by setting config variable advice.detachedHead to false
2022-05-10T12:39:34.8844330Z
2022-05-10T12:39:34.8844863Z HEAD is now at 056a8df Updated Quality.pbix with training hours visuals
2022-05-10T12:39:34.8994122Z ##[section]Finishing: Checkout ***@***.*** to s
2022-05-10T12:39:34.9026429Z ##[section]Starting: Power BI Action: Publish Quality Dataset
2022-05-10T12:39:34.9140544Z ==============================================================================
2022-05-10T12:39:34.9140850Z Task         : Power BI Actions
2022-05-10T12:39:34.9141073Z Description  : Release Task Power BI Actions
2022-05-10T12:39:34.9141288Z Version      : 5.4.32
2022-05-10T12:39:34.9141475Z Author       : Maik van der Gaag
2022-05-10T12:39:34.9141648Z Help         :
2022-05-10T12:39:34.9141898Z ==============================================================================
2022-05-10T12:39:37.5088306Z Starting Power BI Actions extension
2022-05-10T12:39:37.5279486Z ### Required Module is needed. Importing now...
2022-05-10T12:39:37.6811359Z ### Trying to import the incorporated module for PowerBI
2022-05-10T12:39:39.4582347Z Done processing Power BI Actions
2022-05-10T12:39:39.7450162Z ##[error]One or more errors occurred.
2022-05-10T12:39:39.7936153Z ##[section]Finishing: Power BI Action: Publish Quality Dataset
2022-05-10T12:39:39.7990810Z ##[section]Starting: Checkout ***@***.*** to s
2022-05-10T12:39:39.8104099Z ==============================================================================
2022-05-10T12:39:39.8104413Z Task         : Get sources
2022-05-10T12:39:39.8104704Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2022-05-10T12:39:39.8104989Z Version      : 1.0.0
2022-05-10T12:39:39.8105161Z Author       : Microsoft
2022-05-10T12:39:39.8105439Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2022-05-10T12:39:39.8105806Z ==============================================================================
2022-05-10T12:39:40.1462516Z Cleaning any cached credential from repository: XXXXXXAN_QUALITY (Git)
2022-05-10T12:39:40.1527303Z ##[section]Finishing: Checkout ***@***.*** to s
2022-05-10T12:39:40.1587809Z ##[section]Starting: Finalize Job
2022-05-10T12:39:40.1618387Z Cleaning up task key
2022-05-10T12:39:40.1619864Z Start cleaning up orphan processes.
2022-05-10T12:39:40.1645673Z ##[section]Finishing: Finalize Job
2022-05-10T12:39:40.1683895Z ##[section]Finishing: Agent job 1

Warm Regards
Venkat Reddy,
Power Bi Developer | Corporate Reporting | IT |  Balfour Beatty
Mobile: +91 9899873288 | E: ***@***.******@***.***>
6th Floor, N1 Block, Manyata Embassy Business Park, Outer Ring Road, Bengaluru, India, 560045.
www.balfourbeatty.com<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.balfourbeatty.com%2F&data=04%7C01%7Cvenkata.ramana%40balfourbeatty.com%7C82e112dc23944918d87508d8759f5933%7Ca04222fe0c5c40bb842097a219ba514e%7C0%7C0%7C637388674535553128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jyy2v0eozJBy%2B69d%2FcfQNsENmOvC0Vp0xySApp9e2SI%3D&reserved=0> |  ***@***.***  @balfourbeatty<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fbalfourbeatty&data=04%7C01%7Cvenkata.ramana%40balfourbeatty.com%7C82e112dc23944918d87508d8759f5933%7Ca04222fe0c5c40bb842097a219ba514e%7C0%7C0%7C637388674535563128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S6dvTTMdiqYrPpD0PzAMsGLQMEcIuz7RWA8CAdMpFiw%3D&reserved=0> |  ***@***.***  LinkedIn<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fbalfour-beatty-plc%3Ftrk%3Dbiz-companies-cym&data=04%7C01%7Cvenkata.ramana%40balfourbeatty.com%7C82e112dc23944918d87508d8759f5933%7Ca04222fe0c5c40bb842097a219ba514e%7C0%7C0%7C637388674535573116%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ojx0Lmn%2F7Jp%2FLNCgXOAhqpWFUCr7wAsvgTFPoGrHIGI%3D&reserved=0>

***@***.***
