### ISSUE TITLE
Power BI Actions: Set username and password for DQ datasources

### ISSUE THREAD

**Issue by AlexandrStadolnik** [maikvandergaag/msft-extensions#83] opened 2019-04-04 14:02 UTC
Good day, Maik. 

Could you introduce the actions again, as you proposed in the review?
Ability to set username and password for DQ datasources is really missing in this extension.

Thank you

**Comment by maikvandergaag** [comment] 2019-04-04 19:17
I marked the issue as feature request and will check when I will be able to add it again.

**Comment by AlexandrStadolnik** [comment] 2019-04-05 07:51
Thank you very much. Looking forward for the updates.

**Comment by Singley** [comment] 2019-04-09 21:49
@maikvandergaag @AlexandrStadolnik is this feature request encompassing of setting the SQL credentials?  For example, I have confirmed that I can update my Data Source connection using the 'UpdateDataSource' operation in this extension.  However, I cannot set the credentials on that same data set during the same operation.  This leads to the following workflow:

1. Deploy the Power BI report via Devops, updating the DataSource Connection at the same time.  This uses a Service Account.  At this time, my report cannot refresh, as the dataset credentials are invalid.  
2. Update the dataset credentials after logging on the portal with the Service Account
3. The previous step must be done using the Service Account or I have to take ownership with my ID.  If I take ownership away from the Service Account, the 'UpdateDataSource' operation fails on the next deployment.
![image](https://user-images.githubusercontent.com/29473162/55837445-09362780-5ae7-11e9-9ee5-da2359de7125.png)

If the 'Update Data Source' operation allowed credentials to be set during deployment, all of these issues go away, and I finally have my true CI / CD across environments.

Thanks, and I appreciate your efforts to build and support this tool

Mark

**Comment by maikvandergaag** [comment] 2019-04-10 07:27
@Singley : When updating the datasource the account you are using. Must be the owner of the dataset.

I hope to get started on the feature next week, It has been busy times with the birth of my son.

**Comment by Singley** [comment] 2019-04-10 15:23
@maikvandergaag congratulations!  

Thanks for considering this feature- I'll keep an eye on it moving forward.

**Comment by KateHamster** [comment] 2019-04-29 08:59
@maikvandergaag Do you know when this feature will be finally available? We are looking forward for it!

**Comment by hoffe86** [comment] 2019-04-29 11:55
@maikvandergaag We are also interesting in this feature, because we are running our solution in four environments (Development, Integration, Test and Production) with different credentials

**Comment by maikvandergaag** [comment] 2019-04-29 12:01
Hi Everyone,
Sorry that it has been taking that long had some personal stuff (a new son, and moving between houses) I hope to get it in in the next few weeks.

**Comment by maikvandergaag** [comment] 2019-05-20 20:47
Sorry for the late response due to some personal stuff I haven't been able to proccess this hope to be able to do this in august

**Comment by larrysteele** [comment] 2019-08-19 17:42
I'm still looking forward to this feature also. I've actually been working with Microsoft on exactly how to accomplish this, mostly for Odata and passing the token to the dataset to update the credentials using PowerShell. The PS logic appears to work but invalidates the report. I'm hoping to have a resolution shortly with them. Any help you could provide would be amazing and I think most of us would be interested in Odata and SQL auth as they seem to be the most common forms of the Dataset.

**Comment by maikvandergaag** [comment] 2019-08-20 06:58
Hi Larry, thank you for your message, I hope to add some things this week. 
The way it be working is via a connection string or are you looking for a different solution?

**Comment by michaelgoconnor** [comment] 2019-09-16 13:38
Hi @maikvandergaag Just wondering if you have any update on this feature massively appreciate the effort you have put in here.

**Comment by maikvandergaag** [comment] 2019-11-11 09:00
I have added the functionality in the beta version. Are you able to test?

**Comment by michaelgoconnor** [comment] 2019-11-11 14:21
@maikvandergaag Sadly i ended up not using the component and i don't access to environment where I to test anymore, sorry

**Comment by Singley** [comment] 2019-11-11 20:31
I'm out of the country for a week with no access to my work environments.
I'll be happy to test upon my return.  Thanks!

**Comment by maikvandergaag** [comment] 2019-11-11 21:41
If you send me your organization is I will give you access to the beta.

Groetjes,

Maik van der Gaag

________________________________

**Comment by MartinWa** [comment] 2019-11-11 22:32
I am looking for this feature and I could help test it.

**Comment by maikvandergaag** [comment] 2019-11-12 05:46
If you send your organization id of Azure DevOps I can add you to the beta

Groetjes,

Maik van der Gaag

________________________________

**Comment by MartinWa** [comment] 2019-11-13 09:10
I have done some testing with the beta. I do the following three steps:
```
steps:
- task: Development-vanderGaag.maikvandergaag-power-bi-actionsDev.PowerBIActions.PowerBIActions@4
  displayName: 'Power BI Action: Publish'
  inputs:
    serviceConnection: PowerBi
    WorkspaceName: 'Embedded-Dev'
    PowerBIPath: '$(System.DefaultWorkingDirectory)/Statistics-CD/PowerBiReports/basic.pbix'
```
```
steps:
- task: Development-vanderGaag.maikvandergaag-power-bi-actionsDev.PowerBIActions.PowerBIActions@4
  displayName: 'Power BI Action: UpdateDatasource'
  inputs:
    serviceConnection: PowerBi
    Action: UpdateDatasource
    WorkspaceName: 'Embedded-Dev'
    DatasetName: basic
    OldServer: 'xxx.database.windows.net'
    NewServer: 'yyy.database.windows.net'
    OldDatabase: 'zzz'
    NewDatabase: 'ttt'
```
```
steps:
- task: Development-vanderGaag.maikvandergaag-power-bi-actionsDev.PowerBIActions.PowerBIActions@4
  displayName: 'Power BI Action: SQLDirect'
  inputs:
    serviceConnection: PowerBi
    Action: SQLDirect
    WorkspaceName: 'Embedded-Dev'
    DatasetName: basic
    ConnectionString: 'Data Source=yyy.database.windows.net;Initial Catalog=ttt;User ID=sss;Password=uuu'
```

When I run the first time (no report in Power BI) I get the following error:
`Dataset doesn't contain a datasource that matches selector #1`
If I re-run without deleting the report it works.

The above works for Service Principal. I have also tested with User Principal but then I get:
`Exception calling "GetResult" with "0" argument(s): "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.`
Perhaps I have configured the User Principal wrong?

In any case the SQLDirect step seems to work fine (verified by calling the Get Datasources API).

**Comment by maikvandergaag** [comment] 2019-11-13 09:13
Hi Martin,

Thank you for testing, regarding your issue are you using a native app?

**Comment by MartinWa** [comment] 2019-11-13 09:24
I am using a Web type of application

**Comment by maikvandergaag** [comment] 2019-11-13 09:25
When using the User option it should be a native application that’s why youi are  receiving the error.

**Comment by MartinWa** [comment] 2019-11-13 10:21
That worked. It took some time to figure out how to do it thoug so for anyone else with the same problem: Setting _Treat application as a public client_ to true will allow the app registration to work for user principal (resource owner password):
![image](https://user-images.githubusercontent.com/497015/68754635-5c390580-0607-11ea-8626-710c78726ef0.png)

**Comment by MartinWa** [comment] 2019-11-13 12:20
After further testing I still had problems with UpdateDatasource. I did however have the same problems with the non-beta version of the extension so I think that is unrelated. I also found out that I do not need to call UdpdateDatasource as it will be done for me when I call SQLDirect. For me the beta version works. 

Note I have only one datasource in my report. Have not tested with multiple sources.

**Comment by maikvandergaag** [comment] 2019-11-13 14:01
Thanks Martin,

Could you give me some more information on the UpdateDatabsource problems?

**Comment by MartinWa** [comment] 2019-11-14 09:41
This is the output, i removed the text in brackets :
```
2019-11-13T12:11:14.3710996Z ##[section]Starting: Power BI Action: UpdateDatasource
2019-11-13T12:11:14.3817349Z ==============================================================================
2019-11-13T12:11:14.3817431Z Task         : Power BI Actions
2019-11-13T12:11:14.3817499Z Description  : Release Task Power BI Actions
2019-11-13T12:11:14.3817549Z Version      : 4.0.9
2019-11-13T12:11:14.3817618Z Author       : Maik van der Gaag
2019-11-13T12:11:14.3817664Z Help         : 
2019-11-13T12:11:14.3817732Z ==============================================================================
2019-11-13T12:11:15.2454059Z ******************************
2019-11-13T12:11:15.2461310Z ** Service Connection: <guid>
2019-11-13T12:11:15.2488679Z ** TenantId: 
2019-11-13T12:11:15.2495689Z ** ClientId: <guid>
2019-11-13T12:11:15.2503686Z ******************************
2019-11-13T12:11:15.3375838Z FilePattern           : d:\a\r1\a
2019-11-13T12:11:15.3379981Z ClientID         		: <guid>
2019-11-13T12:11:15.3412900Z PassWord            	: ***
2019-11-13T12:11:15.3416542Z Username             	: ***
2019-11-13T12:11:15.3419508Z WorkspaceName         : <workspace>
2019-11-13T12:11:15.3423002Z Overwrite             : True
2019-11-13T12:11:15.3426723Z Create                : True
2019-11-13T12:11:15.3431254Z Action                : UpdateDatasource
2019-11-13T12:11:15.3435284Z Dataset               : <dataset>
2019-11-13T12:11:15.3439409Z Users                 : 
2019-11-13T12:11:15.3443442Z AccessRight           : 
2019-11-13T12:11:15.3446866Z OldServer             : <xxx>.database.windows.net
2019-11-13T12:11:15.3449659Z NewServer             : <yyy>.database.windows.net
2019-11-13T12:11:15.3453158Z OldDatabase           : <sss>
2019-11-13T12:11:15.3456988Z NewDatabase           : <ttt>
2019-11-13T12:11:15.3459910Z OldUrl                : 
2019-11-13T12:11:15.3463130Z NewUrl                : 
2019-11-13T12:11:15.3467777Z DatasourceType        : Sql
2019-11-13T12:11:15.3470657Z UpdateAll             : False
2019-11-13T12:11:15.3475284Z ClientSecret          : 
2019-11-13T12:11:15.3479119Z TenantId              : 
2019-11-13T12:11:15.3483926Z Service Principals    : 
2019-11-13T12:11:15.3503107Z Logging in with a User Principal
2019-11-13T12:11:15.7224124Z Trying to update the datasource
2019-11-13T12:11:15.7376783Z Getting Power BI Workspace properties; <workspace>
2019-11-13T12:11:16.4559461Z ##[error]Dataset doesn't contain a datasource that matches selector #1
2019-11-13T12:11:16.4840165Z ##[section]Finishing: Power BI Action: UpdateDatasource

```

**Comment by maikvandergaag** [comment] 2020-08-15 06:42
Closing this issue if you need further assistant please let me know

**Closed by maikvandergaag** 2020-08-15 06:42 UTC
Labels: feature request
