### ISSUE TITLE
Update dataset parameter using service principal doesn't seem to work.

### ISSUE THREAD

**Issue by albertlinga** [maikvandergaag/msft-extensions#215] opened 2020-10-05 14:50 UTC
I have a service connection that uses a service principal with Tenant.ReadWrite.All permission.

I have two steps on my pipeline:
1. Upload a pbix file. This dataset has a parameter with a default value.
2. Update the parameter for the uploaded dataset to a new value.

Base on further research, the service principal or whichever user context the pipeline runs must own the dataset. Within the update dataset parameter function there should be a call to "https://api.powerbi.com/v1.0/myorg/groups/{groupid}/datasets/{datasetid}/Default.TakeOver"

File being referenced is https://github.com/maikvandergaag/msft-extensions/blob/master/azuredevops/powerbiactions-new/powerbiactionsnew/ps_modules/PowerBi/powerbi.psm1

This might be the same issue for other tasks that doesn't seem to be working.

**Comment by albertlinga** [comment] 2020-10-05 17:19
I have overlooked "Take Dataset Ownership" action.

**Comment by albertlinga** [comment] 2020-10-05 17:34
I've used Take Ownership and it still doesn't work.

1. Upload a pbix file. This dataset has a parameter with a default value.
2. Service principal takes ownership.
3. Update the parameter for the uploaded dataset to a new value.

**Comment by maikvandergaag** [comment] 2020-10-05 17:36
Hi Albert,

Can you share some more information?

**Comment by albertlinga** [comment] 2020-10-05 17:45
Hi @maikvandergaag,

May I know what info you need?

**Comment by maikvandergaag** [comment] 2020-10-05 17:47
The log of the task when run in debug mode. To run your pipeline in debug mode add the system.debug variable with the value true to your pipeline. 

And if you could also share the configuration of the task

**Comment by nitin-AET-Tankers** [comment] 2020-10-06 08:37
> being referen

@albertlinga  Please ensure that another task **after** uploading report and **before** updating parameters; i.e. an action to 'Take over Ownership'. Hope you have configured the JSON value rightly in the task; For example I have used as below-
The name in JSON should be same as the Parameter name used in PBI reports.
[
{
"name": "DB_ServerInstance",
"newValue": "val"
},
{
"name": "DB_Name",
"newValue": "val"
},
{
"name": "DB_Name_Common",
"newValue": "val"
}
]

**Comment by albertlinga** [comment] 2020-10-06 09:48
@nitin-AET-Tankers that's what I did already https://github.com/maikvandergaag/msft-extensions/issues/215#issuecomment-703779155

@maikvandergaag  will document and upload the configuration and debug info.

**Comment by albertlinga** [comment] 2020-10-08 11:13
Here are my configuration
![step-1](https://user-images.githubusercontent.com/28690177/95451410-50ca9780-099a-11eb-8009-b6607c24ee1c.png)
![step-2](https://user-images.githubusercontent.com/28690177/95451414-51fbc480-099a-11eb-9cd3-8fd8f4117b6d.png)
![step-3](https://user-images.githubusercontent.com/28690177/95451416-52945b00-099a-11eb-8509-391b694316ec.png)

**Comment by maikvandergaag** [comment] 2020-10-08 11:15
Could you also share the log of the task when run in debug mode. To run your pipeline in debug mode add the system.debug variable with the value true to your pipeline.

**Comment by nitin-AET-Tankers** [comment] 2020-10-08 11:20
@maikvandergaag I may not have tested this scenario that used a particular dataset Name; if code is right then maybe an issue with ""

**Comment by albertlinga** [comment] 2020-10-08 11:37
2020-10-08T11:25:36.1053455Z ##[debug]11:25:36 AM - Connect-PowerBIServiceAccount begin processing with ParameterSet ServicePrincipal.
2020-10-08T11:25:36.1069566Z ##[debug]11:25:36 AM - Cmdlet version: 1.0.867.0
2020-10-08T11:25:36.1092824Z ##[debug]Updated Azure AD authority with -Tenant specified, new value: https://login.microsoftonline.com/***
2020-10-08T11:25:36.6952592Z ##[debug]11:25:36 AM - Connect-PowerBIServiceAccount end processing.
2020-10-08T11:25:36.7592046Z ##[debug]INPUT_POWERBIPATH: 'D:\a\1\s'
2020-10-08T11:25:36.7610761Z ##[debug]INPUT_WORKSPACENAME: 'My Visualizations'
2020-10-08T11:25:36.7631046Z ##[debug]INPUT_OVERWRITE: 'true'
2020-10-08T11:25:36.7655590Z ##[debug] Converted to bool: True
2020-10-08T11:25:36.7675311Z ##[debug]INPUT_CREATE: 'true'
2020-10-08T11:25:36.7688304Z ##[debug] Converted to bool: True
2020-10-08T11:25:36.7706015Z ##[debug]INPUT_ACTION: 'UpdateParameters'
2020-10-08T11:25:36.7723376Z ##[debug]INPUT_DATASETNAME: 'headcount-0'
2020-10-08T11:25:36.7743847Z ##[debug]INPUT_OLDURL (empty)
2020-10-08T11:25:36.7779449Z ##[debug]INPUT_NEWURL (empty)
2020-10-08T11:25:36.7796762Z ##[debug]INPUT_OLDSERVER (empty)
2020-10-08T11:25:36.7814137Z ##[debug]INPUT_NEWSERVER (empty)
2020-10-08T11:25:36.7830976Z ##[debug]INPUT_OLDDATABASE (empty)
2020-10-08T11:25:36.7847384Z ##[debug]INPUT_GROUPOBJECTIDS (empty)
2020-10-08T11:25:36.7864917Z ##[debug]INPUT_NEWDATABASE (empty)
2020-10-08T11:25:36.7882086Z ##[debug]INPUT_PERMISSION (empty)
2020-10-08T11:25:36.7900681Z ##[debug]INPUT_USERS (empty)
2020-10-08T11:25:36.7918496Z ##[debug]INPUT_DATASOURCETYPE: 'Sql'
2020-10-08T11:25:36.7936188Z ##[debug]INPUT_UPDATEALL: 'false'
2020-10-08T11:25:36.7949062Z ##[debug] Converted to bool: False
2020-10-08T11:25:36.7966434Z ##[debug]INPUT_SERVICEPRINCIPALS (empty)
2020-10-08T11:25:36.7983362Z ##[debug]INPUT_CONNECTIONSTRING (empty)
2020-10-08T11:25:36.8001336Z ##[debug]INPUT_PARAMETERINPUT: '[{'name': 'ClientSiteID', 'newValue': '00000000-0000-0000-0000-000000000001'}]'
2020-10-08T11:25:36.8023515Z ##[debug]WorkspaceName         : My Visualizations
2020-10-08T11:25:36.8036754Z ##[debug]Create                : True
2020-10-08T11:25:36.8051487Z ##[debug]Dataset               : headcount-0
2020-10-08T11:25:36.8062951Z ##[debug]Update Json     	: [{'name': 'ClientSiteID', 'newValue': '00000000-0000-0000-0000-000000000001'}]
2020-10-08T11:25:36.8069876Z Trying to update the dataset parameters
2020-10-08T11:25:36.8164918Z Getting Power BI Workspace properties; My Visualizations
2020-10-08T11:25:36.8239866Z ##[debug]11:25:36 AM - Get-PowerBIAccessToken begin processing with ParameterSet __AllParameterSets.
2020-10-08T11:25:36.8253005Z ##[debug]11:25:36 AM - Cmdlet version: 1.0.867.0
2020-10-08T11:25:36.8269927Z ##[debug]11:25:36 AM - Get-PowerBIAccessToken end processing.
2020-10-08T11:25:36.8290461Z ##[debug]Trying to invoke api: https://api.powerbi.com/v1.0/myorg/groups
2020-10-08T11:25:36.8338575Z ##[debug]GET https://api.powerbi.com/v1.0/myorg/groups with 0-byte payload
2020-10-08T11:25:37.7098378Z ##[debug]received -1-byte response of content type application/json; odata.metadata=minimal; odata.streaming=true
2020-10-08T11:25:37.7099629Z ##[debug]Trying to find workspace: My Visualizations
2020-10-08T11:25:37.7312861Z ##[debug]Processed: ##vso[task.setvariable variable=PowerBIActions.WorkspaceId]1F24ad95-545a-414c-9fee-efcc102f328a
2020-10-08T11:25:37.7327717Z Done running Power BI Actions extension.
2020-10-08T11:25:37.7333979Z ##[debug]Leaving D:\a\_tasks\PowerBIActions_d5b7fec6-2b25-4742-905b-0dad97687df5\5.2.0\run.ps1.
2020-10-08T11:25:37.7517592Z ##[section]Finishing: Power BI Action: UpdateParameters

**Comment by albertlinga** [comment] 2020-10-08 11:39
Above is part of the debug log for the update parameter. As you can see after it tried to find the workspace and I believe it was able to, there's no subsequent logs for invoking the api to update the parameter. This is the same case for taking ownership. The first step though was able to work and publish the pbix file and I saw subsequent commands for invoking api's publishing the pbix file.

**Comment by nitin-AET-Tankers** [comment] 2020-10-08 11:54
@albertlinga  you are using 'my workspace' right? Whats effect in the dataset setting--> parameters in PowerBI online before and after publishing the report?

**Comment by albertlinga** [comment] 2020-10-08 12:05
It's a different workspace name actually, I just modified the logs to change some values (worried I might be sharing too much info). 

The pbix file has a default empty guid value for the parameter, this parameter is of type Text. So when it's published it has empty GUID. After the update parameter step I'm expecting it to change to 00000000-0000-0000-0000-000000000001 (Note: the 1 in the end). However when I go to powerbi.com go the settings of that dataset, take over the ownership (so I can see the value of the parameter), and see that it's still an empty GUID. So essentially it wasn't updated. No errors on the step as you can see in the logs but I also don't see any log entries that invoked the update parameter rest api.

**Comment by nitin-AET-Tankers** [comment] 2020-10-08 12:11
@albertlinga  Let Maik also check on this, meanwhile can you please -
1. Close all incognito tabs and then open new Incognito tab
2. Go to https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/updateparametersingroup
3. Login using the same account that you are trying to use in PowerBI Actions (if not SPN)
4. Key in the parameters and copy the same JSON in pipeline and execute.

Let us know if any errors

**Comment by albertlinga** [comment] 2020-10-08 12:12
Login using the same account that you are trying to use in PowerBI Actions (if not SPN) - I am using a service principal

**Comment by nitin-AET-Tankers** [comment] 2020-10-08 12:20
> Login using the same account that you are trying to use in PowerBI Actions (if not SPN) - I am using a service principal
If you have a test or empty workspace, can you publish this dataset to that (and choose update All in pipeline)...? I will also try to replicate this in my end; currently I am in the middle of another testing wherein my auth is failing 😮

**Comment by nitin-AET-Tankers** [comment] 2020-10-08 15:02
@maikvandergaag  please help to check- in function Set-PowerBIDataSetOwnership  --  if ($UpdateAll) { } is the reason; 
 I tried to take ownership for a particular dataset and it wasn't successful. Am sorry, I didn't test this scenario as mine was a bulk case.

Solution: May have to use 'updateDataset' variable as you have done for other case.

**Comment by albertlinga** [comment] 2020-10-08 16:16
I see what you're saying. There's no else statement for if ($UpdateAll) {}

I'll try to submit a pull request but I'll probably just target changing powerbi.psm1. If you have unit tests on this project I might not be able to change those for now.

**Comment by maikvandergaag** [comment] 2020-10-08 16:50
Hi guys, just fixed it in the beta control @albertlinga do you have access to the beta? If not if you supply me with your organization I can give you access to the beta

**Comment by albertlinga** [comment] 2020-10-08 17:21
It worked on my usecase now. Thank you @maikvandergaag. Shall I close this ticket?

**Comment by maikvandergaag** [comment] 2020-10-08 17:45
Yes that would be great

Groetjes,

Maik van der Gaag
________________________________
Van: -=Albert=- <notifications@github.com>
Verzonden: Thursday, October 8, 2020 7:21:37 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Update dataset parameter using service principal doesn't seem to work. (#215)


It worked on my usecase now. Thank you @maikvandergaag<https://github.com/maikvandergaag>. Shall I close this ticket?

**Comment by albertlinga** [comment] 2020-10-08 17:53
Oh sorry to jump to conclusion. I had the last step to refresh the dataset, made sure the update all dataset option is unchecked and set the datasetname. However upon running the pipeline logs showed it processing all my datasets in the workspace. I'm only expecting 1 console log entry for "Processing dataset <name>". I checked your code and it seems right already so I'm not sure what the issue is.

`Function New-DatasetRefresh {
    Param(
        [parameter(Mandatory = $true)][string]$WorkspaceName,
        [parameter(Mandatory = $false)][string]$DataSetName,
        [parameter(Mandatory = $false)][string]$UpdateAll = $false
    )

    $groupPath = Get-PowerBIGroupPath -WorkspaceName $WorkspaceName
    if ($groupPath) {
        $datasets = Get-PowerBiDataSets -GroupPath $groupPath
        foreach ($dataset in $datasets) {

            if ($dataset.name -eq $datasetName -and !$UpdateAll) {
                $updateDataset = $true
            }

            if ($UpdateAll -or $updateDataset) {
                if ($dataset) {

                    Write-Host "Processing dataset $($dataset.name)"
                    if ($dataset.isRefreshable -eq $true) {
                        $url = $powerbiUrl + $GroupPath + "/datasets/$($dataset.id)/refreshes"
                        Invoke-API -Url $url -Method "Post" -ContentType "application/json"
                    }
                    else {
                        Write-Warning "Dataset: $($dataset.name) cannot be refreshed!"
                    }


                }
            }
        }
    }
    else {
        Write-Error "Workspace: $WorkspaceName could not be found"
    }   `

**Comment by maikvandergaag** [comment] 2020-10-08 17:55
Are you sure you are running the beta version? And do you have the log?

Groetjes,

Maik van der Gaag
________________________________
Van: -=Albert=- <notifications@github.com>
Verzonden: Thursday, October 8, 2020 7:53:47 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Update dataset parameter using service principal doesn't seem to work. (#215)


Oh sorry to jump to conclusion. I had the last step to refresh the dataset, made sure the update all dataset option is unchecked and set the datasetname. However upon running the pipeline logs showed it processing all my datasets in the workspace. I'm only expecting 1 console log entry for "Processing dataset ". I checked your code and it seems right already so I'm not sure what the issue is.

`Function New-DatasetRefresh {
Param(
[parameter(Mandatory = $true)][string]$WorkspaceName,
[parameter(Mandatory = $false)][string]$DataSetName,
[parameter(Mandatory = $false)][string]$UpdateAll = $false
)

$groupPath = Get-PowerBIGroupPath -WorkspaceName $WorkspaceName
if ($groupPath) {
    $datasets = Get-PowerBiDataSets -GroupPath $groupPath
    foreach ($dataset in $datasets) {

        if ($dataset.name -eq $datasetName -and !$UpdateAll) {
            $updateDataset = $true
        }

        if ($UpdateAll -or $updateDataset) {
            if ($dataset) {

                Write-Host "Processing dataset $($dataset.name)"
                if ($dataset.isRefreshable -eq $true) {
                    $url = $powerbiUrl + $GroupPath + "/datasets/$($dataset.id)/refreshes"
                    Invoke-API -Url $url -Method "Post" -ContentType "application/json"
                }
                else {
                    Write-Warning "Dataset: $($dataset.name) cannot be refreshed!"
                }


            }
        }
    }
}
else {
    Write-Error "Workspace: $WorkspaceName could not be found"
}   `

**Comment by albertlinga** [comment] 2020-10-08 17:57
I uninstalled the previous power bi extension and installed the DEV one, I suppose this is the beta version? Recreated my pipeline steps. 

![image](https://user-images.githubusercontent.com/28690177/95496022-d1a58580-09d2-11eb-8dd3-6c6ac4deece3.png)

**Comment by maikvandergaag** [comment] 2020-10-08 17:58
Yes that is it could you share the logs

Groetjes,

Maik van der Gaag
________________________________
Van: -=Albert=- <notifications@github.com>
Verzonden: Thursday, October 8, 2020 7:58:02 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Update dataset parameter using service principal doesn't seem to work. (#215)


I uninstalled the previous power bi extension and installed the DEV one, I suppose this is the beta version? Recreated my pipeline steps.

[image]<https://user-images.githubusercontent.com/28690177/95496022-d1a58580-09d2-11eb-8dd3-6c6ac4deece3.png>

**Comment by albertlinga** [comment] 2020-10-08 18:00
I didn't enable debug but here's the console log with debug false

Starting: Power BI Action: DataRefresh
==============================================================================
Task         : Power BI Actions
Description  : Release Task Power BI Actions
Version      : 5.2.3
Author       : Maik van der Gaag
Help         : 
==============================================================================
Starting Power BI Actions extension
### Required Module is needed. Importing now...
### Trying to import the incorporated module for PowerBI
Trying to refresh Dataset
Getting Power BI Workspace properties; My Visualizations
Processing dataset dataset 1

Processing dataset test

Processing dataset test 2

Processing dataset test 3

Processing dataset headcount-0

Done processing Power BI Actions
Done running Power BI Actions extension.
Finishing: Power BI Action: DataRefresh

**Comment by maikvandergaag** [comment] 2020-10-08 18:02
I think I know what is wrong. It shows the processing message but does not do anything.

Will update the source

Groetjes,

Maik van der Gaag
________________________________
Van: -=Albert=- <notifications@github.com>
Verzonden: Thursday, October 8, 2020 8:00:42 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Update dataset parameter using service principal doesn't seem to work. (#215)


I didn't enable debug but here's the console log with debug false

Starting: Power BI Action: DataRefresh
Task : Power BI Actions
Description : Release Task Power BI Actions
Version : 5.2.3
Author : Maik van der Gaag
Help :

Starting Power BI Actions extension

Required Module is needed. Importing now...
Trying to import the incorporated module for PowerBI

Trying to refresh Dataset
Getting Power BI Workspace properties; My Visualizations
Processing dataset dataset 1

Processing dataset test

Processing dataset test 2

Processing dataset test 3

Processing dataset headcount-0

Done processing Power BI Actions
Done running Power BI Actions extension.
Finishing: Power BI Action: DataRefresh

**Comment by maikvandergaag** [comment] 2020-10-08 18:09
Give it 5 min then the version will be 5.2.4

**Comment by maikvandergaag** [comment] 2020-10-08 18:11
sorry will be version 5.2.5

**Comment by albertlinga** [comment] 2020-10-08 18:15
but the thing is 
`if ($UpdateAll -or $updateDataset) {
                if ($dataset) {

                    Write-Host "Processing dataset $($dataset.name)"`

if the dataset name does not match the parameter and Update all is false then processing message shouldn't appear.

**Comment by maikvandergaag** [comment] 2020-10-08 18:21
5.2.5 should automatically be installed and should be there now.

**Comment by albertlinga** [comment] 2020-10-08 18:31
Now it errors out with this message on all my steps

2020-10-08T18:27:50.3672536Z ##[error]Cannot bind parameter because parameter 'Function' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".

**Comment by maikvandergaag** [comment] 2020-10-08 18:32
Hi Albert could you then please share your log

Groetjes,

Maik van der Gaag
________________________________
Van: -=Albert=- <notifications@github.com>
Verzonden: Thursday, October 8, 2020 8:31:19 PM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [maikvandergaag/msft-extensions] Update dataset parameter using service principal doesn't seem to work. (#215)


Now it errors out with this message on all my steps

2020-10-08T18:27:50.3672536Z ##[error]Cannot bind parameter because parameter 'Function' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".

**Comment by albertlinga** [comment] 2020-10-08 18:38
2020-10-08T18:36:04.6382936Z ##[debug]Evaluating condition for step: 'Power BI Action: Publish'
2020-10-08T18:36:04.6384768Z ##[debug]Evaluating: succeeded()
2020-10-08T18:36:04.6385963Z ##[debug]Evaluating succeeded:
2020-10-08T18:36:04.6387247Z ##[debug]=> True
2020-10-08T18:36:04.6387926Z ##[debug]Result: True
2020-10-08T18:36:04.6388558Z ##[section]Starting: Power BI Action: Publish
2020-10-08T18:36:04.6530272Z ==============================================================================
2020-10-08T18:36:04.6530625Z Task         : Power BI Actions
2020-10-08T18:36:04.6530923Z Description  : Release Task Power BI Actions
2020-10-08T18:36:04.6531166Z Version      : 5.2.5
2020-10-08T18:36:04.6531414Z Author       : Maik van der Gaag
2020-10-08T18:36:04.6531647Z Help         : 
2020-10-08T18:36:04.6532077Z ==============================================================================
2020-10-08T18:36:05.7094742Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-10-08T18:36:05.8517134Z Starting Power BI Actions extension
2020-10-08T18:36:05.8664690Z ##[debug]Entering D:\a\_tasks\PowerBIActions_83363fce-bb69-5220-ab94-4f0ae09369a3\5.2.5\run.ps1.
2020-10-08T18:36:05.8761746Z ### Required Module is needed. Importing now...
2020-10-08T18:36:05.8823438Z ##[debug]Loading module from path 'D:\a\_tasks\PowerBIActions_83363fce-bb69-5220-ab94-4f0ae09369a3\5.2.5\ps_modules\MicrosoftPowerBIMgmt.Profile\1.0.867\MicrosoftPowerBIMgmt.Profile.psd1'.
2020-10-08T18:36:05.8907333Z ##[debug]Loading 'TypesToProcess' from path 'D:\a\_tasks\PowerBIActions_83363fce-bb69-5220-ab94-4f0ae09369a3\5.2.5\ps_modules\MicrosoftPowerBIMgmt.Profile\1.0.867\Microsoft.PowerBI.Commands.Profile.types.ps1xml'.
2020-10-08T18:36:05.8948882Z ##[debug]Loading 'FormatsToProcess' from path 'D:\a\_tasks\PowerBIActions_83363fce-bb69-5220-ab94-4f0ae09369a3\5.2.5\ps_modules\MicrosoftPowerBIMgmt.Profile\1.0.867\Microsoft.PowerBI.Commands.Profile.format.ps1xml'.
2020-10-08T18:36:05.9508446Z ##[debug]Populating RepositorySourceLocation property for module MicrosoftPowerBIMgmt.Profile.
2020-10-08T18:36:05.9546427Z ##[debug]Loading module from path 'D:\a\_tasks\PowerBIActions_83363fce-bb69-5220-ab94-4f0ae09369a3\5.2.5\ps_modules\MicrosoftPowerBIMgmt.Profile\1.0.867\.\lib\netstandard2.0\Microsoft.PowerBI.Commands.Profile.dll'.
2020-10-08T18:36:05.9690371Z ##[debug]Exporting cmdlet 'Connect-PowerBIServiceAccount'.
2020-10-08T18:36:05.9725516Z ##[debug]Exporting cmdlet 'Disconnect-PowerBIServiceAccount'.
2020-10-08T18:36:05.9756177Z ##[debug]Exporting cmdlet 'Get-PowerBIAccessToken'.
2020-10-08T18:36:05.9810957Z ##[debug]Exporting cmdlet 'Invoke-PowerBIRestMethod'.
2020-10-08T18:36:05.9845900Z ##[debug]Exporting cmdlet 'Resolve-PowerBIError'.
2020-10-08T18:36:05.9877905Z ##[debug]Importing cmdlet 'Connect-PowerBIServiceAccount'.
2020-10-08T18:36:05.9912599Z ##[debug]Importing cmdlet 'Disconnect-PowerBIServiceAccount'.
2020-10-08T18:36:05.9948713Z ##[debug]Importing cmdlet 'Get-PowerBIAccessToken'.
2020-10-08T18:36:05.9986278Z ##[debug]Importing cmdlet 'Invoke-PowerBIRestMethod'.
2020-10-08T18:36:06.0018629Z ##[debug]Importing cmdlet 'Resolve-PowerBIError'.
2020-10-08T18:36:06.0070322Z ##[debug]Importing alias 'Add-PowerBIServiceAccount'.
2020-10-08T18:36:06.0150856Z ##[debug]Importing alias 'Login-PowerBI'.
2020-10-08T18:36:06.0152274Z ##[debug]Importing alias 'Login-PowerBIServiceAccount'.
2020-10-08T18:36:06.0215203Z ##[debug]Importing alias 'Logout-PowerBI'.
2020-10-08T18:36:06.0258773Z ##[debug]Importing alias 'Logout-PowerBIServiceAccount'.
2020-10-08T18:36:06.0289295Z ##[debug]Importing alias 'Remove-PowerBIServiceAccount'.
2020-10-08T18:36:06.0317491Z ##[debug]Importing alias 'Set-PowerBIServiceAccount'.
2020-10-08T18:36:06.0337458Z ### Trying to import the incorporated module for PowerBI
2020-10-08T18:36:06.0371166Z ##[debug]Loading module from path 'D:\a\_tasks\PowerBIActions_83363fce-bb69-5220-ab94-4f0ae09369a3\5.2.5\ps_modules\PowerBi\PowerBi.psm1'.
2020-10-08T18:36:06.1036995Z ##[debug]Caught exception from task script.
2020-10-08T18:36:06.1093752Z ##[debug]Error record:
2020-10-08T18:36:06.1795046Z ##[debug]Export-ModuleMember : Cannot bind parameter because parameter 'Function' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
2020-10-08T18:36:06.1833260Z ##[debug]At D:\a\_tasks\PowerBIActions_83363fce-bb69-5220-ab94-4f0ae09369a3\5.2.5\ps_modules\PowerBi\PowerBi.psm1:753 char:57
2020-10-08T18:36:06.1855922Z ##[debug]+ ... port-ModuleMember -Function "*-*" Export-ModuleMember -Function "*-*"
2020-10-08T18:36:06.1885773Z ##[debug]+                                                           ~~~~~~~~~
2020-10-08T18:36:06.1917327Z ##[debug]    + CategoryInfo          : InvalidArgument: (:) [Export-ModuleMember], ParentContainsErrorRecordException
2020-10-08T18:36:06.2118806Z ##[debug]    + FullyQualifiedErrorId : ParameterAlreadyBound,Microsoft.PowerShell.Commands.ExportModuleMemberCommand
2020-10-08T18:36:06.2174492Z ##[debug] 
2020-10-08T18:36:06.2430471Z ##[debug]Script stack trace:
2020-10-08T18:36:06.3436406Z ##[debug]at <ScriptBlock>, D:\a\_tasks\PowerBIActions_83363fce-bb69-5220-ab94-4f0ae09369a3\5.2.5\ps_modules\PowerBi\PowerBi.psm1: line 753
2020-10-08T18:36:06.3465011Z ##[debug]at <ScriptBlock><Begin>, D:\a\_tasks\PowerBIActions_83363fce-bb69-5220-ab94-4f0ae09369a3\5.2.5\run.ps1: line 12
2020-10-08T18:36:06.3486741Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-10-08T18:36:06.3504612Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-10-08T18:36:06.3527356Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-10-08T18:36:06.3549883Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-10-08T18:36:06.3577807Z ##[debug]Exception:
2020-10-08T18:36:06.3636667Z ##[debug]System.Management.Automation.ParentContainsErrorRecordException: Cannot bind parameter because parameter 'Function' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
2020-10-08T18:36:06.4045853Z ##[error]Cannot bind parameter because parameter 'Function' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
2020-10-08T18:36:06.4071944Z ##[debug]Processed: ##vso[task.logissue type=error]Cannot bind parameter because parameter 'Function' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
2020-10-08T18:36:06.4083452Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-10-08T18:36:06.4533857Z ##[section]Finishing: Power BI Action: Publish

**Comment by albertlinga** [comment] 2020-10-08 18:39
You got multiple  export  at the end of the file


Export-ModuleMember -Function "*-*" Export-ModuleMember -Function "*-*" 
Export-ModuleMember -Function "*-*" 
Export-ModuleMember -Function "*-*"

**Comment by maikvandergaag** [comment] 2020-10-08 18:41
Yes I have removed it I think something went wrong with the merge from @nitin-AET-Tankers. But it should be fixed in 5 min
it should be version 5.2.6

**Comment by nitmatgeo** [comment] 2020-10-08 18:43
@maikvandergaag @albertlinga 
Oops am sorry :disappointed: I failed to notice that during my merge... wasted a version number -_-

**Comment by maikvandergaag** [comment] 2020-10-08 18:45
No problem, I should have seen it.

I'm very happy with all the help you are offering

**Comment by albertlinga** [comment] 2020-10-08 18:45
Again I haven't really read the whole code tree, but I think unit tests would help a lot on catching errors and bugs.

**Comment by maikvandergaag** [comment] 2020-10-08 18:47
@albertlinga I totally agree with you. But did not have any time to add it but it is on my wish list

**Comment by albertlinga** [comment] 2020-10-08 18:49
Will try to contribute one of these days. Thank you for all your help though. This is really a very helpful extension.

**Comment by nitmatgeo** [comment] 2020-10-08 18:50
> No problem, I should have seen it.
> 
> I'm very happy with all the help you are offering

:smiling_face_with_three_hearts: 
I will test again tomorrow and confirm on gateway.. it was working before, I had an error due to a dataset and the deployment failed. That's why attempted changing error to warning. Will update :)

**Closed** 2020-10-12 08:50 UTC

**Comment by kashanico** [comment] 2020-11-20 21:56
Have the changes in the beta from this issue been pushed to public extension? @maikvandergaag

**Comment by maikvandergaag** [comment] 2020-11-21 06:26
It should have been pushed are you experiencing issues?
